### ISSUE TITLE
Error: Checksums do not match on 'conveyor.is_email_registered' call

### ISSUE THREAD

**Issue by gregory-latinier** [steemit/faucet#125]
Using the last login / password provided by @bonustrack for the conveyor calls I have this error:

`Error: Checksums do not match`

when I call the `conveyor.is_email_registered` endpoint on the check email step for instance.

Nothing changed in the code, it's the error I have since this morning.
The `STEEMJS_URL` is configured to use : https://api.steemit.com
  
With complete details:

```
Error: Checksums do not match
    at Object.toBits (D:\Dev\Projects\Steemit\faucet\node_modules\@steemit\libcrypto\lib\crypto.js:3166:13)
    at Object.deserializePrivateKey (D:\Dev\Projects\Steemit\faucet\node_modules\@steemit\libcrypto\lib\crypto.js:3387:42)
    at Function.PrivateKey.from (D:\Dev\Projects\Steemit\faucet\node_modules\@steemit\libcrypto\lib\crypto.js:3463:26)
    at sign (D:\Dev\Projects\Steemit\faucet\node_modules\@steemit\rpc-auth\lib\index.js:114:42)
    at Steem.signedCall (D:\Dev\Projects\Steemit\faucet\node_modules\@steemit\steem-js\lib\api\index.js:215:45)
    at Steem.signedCall (internal/util.js:227:26)
```

**Comment by gregory-latinier** [comment]
It was due to a wrong key
