### ISSUE TITLE
Request Email Failed

### ISSUE THREAD

**Issue by dacom-dark-sun** [steemit/faucet#223]
After success first step, i enter email, and click "Continue", but have error:
An unexpected error occurred. Please try again later

 `{error: {type: "error_api_general", field: "general"}}`

Jussi Output:
```{"funcName": "cache_jsonrpc_response", "lineno": 111, "msecs": 289.935827255249, "message": "jsonrpc error response", "name": "jussi.cache.cache_group", "timestamp": "2018-02-20T06:55:45.1519109745UTC", "severity": "INFO"}
{"funcName": "cache_jsonrpc_response", "lineno": 111, "msecs": 138.49186897277832, "message": "jsonrpc error response", "name": "jussi.cache.cache_group", "timestamp": "2018-02-20T06:55:47.1519109747UTC", "severity": "INFO"}
{"funcName": "cache_jsonrpc_response", "lineno": 111, "msecs": 49.56793785095215, "message": "jsonrpc error response", "name": "jussi.cache.cache_group", "timestamp": "2018-02-20T06:55:49.1519109749UTC", "severity": "INFO"}
{"timestamp":"2018-02-20T06:55:45+00:00","remote_addr":"113.185.14.149","request":"POST / HTTP/1.1","status":200,"body_bytes_sent":69,"request_time":0.477,"http_referrer":"https://signup.dacom.io/","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"000213217665232108","x_jussi_response_time":"0.47440288399957353","x_jussi_namespace":"overseer","x_jussi_api":"False","x_jussi_method":"collect","x_jussi_params":"['signup', {'step': 'username', 'stepNumber': 0}]","upstream_connect_time":0.001,"upstream_response_time":0.477,"upstream_header_time":0.477,"upstream_response_length":69,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:46+00:00","remote_addr":"195.201.61.139","request":"POST / HTTP/1.1","status":200,"body_bytes_sent":20,"request_time":0.006,"http_referrer":"-","http_user_agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"000975753012385664","x_jussi_response_time":"0.003082682000240311","x_jussi_namespace":"steemd","x_jussi_api":"database_api","x_jussi_method":"get_accounts","x_jussi_params":"[['dacom']]","upstream_connect_time":0.000,"upstream_response_time":0.005,"upstream_header_time":0.005,"upstream_response_length":20,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:47+00:00","remote_addr":"113.185.22.191","request":"POST / HTTP/1.1","status":200,"body_bytes_sent":69,"request_time":2.326,"http_referrer":"https://signup.dacom.io/","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"001055328074541208","x_jussi_response_time":"2.3235824840012356","x_jussi_namespace":"overseer","x_jussi_api":"False","x_jussi_method":"collect","x_jussi_params":"['signup', {'step': 'username', 'stepNumber': 0}]","upstream_connect_time":0.000,"upstream_response_time":2.326,"upstream_header_time":2.326,"upstream_response_length":69,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:49+00:00","remote_addr":"113.185.22.191","request":"POST / HTTP/1.1","status":200,"body_bytes_sent":69,"request_time":0.433,"http_referrer":"https://signup.dacom.io/","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"000742423367873529","x_jussi_response_time":"0.4307382519982639","x_jussi_namespace":"overseer","x_jussi_api":"False","x_jussi_method":"collect","x_jussi_params":"['signup', {'step': 'email', 'stepNumber': 1}]","upstream_connect_time":0.000,"upstream_response_time":0.433,"upstream_header_time":0.433,"upstream_response_length":69,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:55+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.000,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:55+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.000,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:55+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:56+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:56+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:55:58+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.000,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"funcName": "log", "lineno": 164, "msecs": 45.16196250915527, "message": "{'jsonrpc': '2.0', 'error': {'code': -32603, 'message': 'Internal Error', 'data': {'error_id': '1ece6d83-c9a2-4651-a71e-14f5a5c90971', 'request': {'amzn_trace_id': None, 'jussi_request_id': None}, 'exception': TimeoutError()}}}", "name": "jussi.errors", "timestamp": "2018-02-20T06:56:01.1519109761UTC", "severity": "ERROR", "exc_info": "Traceback (most recent call last):\n  File \"/app/.venv/lib/python3.6/site-packages/sanic/app.py\", line 503, in handle_request\n    response = await response\n  File \"/app/jussi/handlers.py\", line 37, in handle_jsonrpc\n    jsonrpc_requests)\n  File \"/app/jussi/handlers.py\", line 117, in dispatch_single\n    jsonrpc_request)\n  File \"/app/jussi/handlers.py\", line 99, in fetch_http\n    timeout=jsonrpc_request.upstream.timeout) as resp:\n  File \"/app/.venv/lib/python3.6/site-packages/aiohttp/client.py\", line 690, in __aenter__\n    self._resp = yield from self._coro\n  File \"/app/.venv/lib/python3.6/site-packages/aiohttp/client.py\", line 277, in _request\n    yield from resp.start(conn, read_until_eof)\n  File \"/app/.venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py\", line 637, in start\n    self._continue = None\n  File \"/app/.venv/lib/python3.6/site-packages/aiohttp/helpers.py\", line 727, in __exit__\n    raise asyncio.TimeoutError from None\nconcurrent.futures._base.TimeoutError"}
{"funcName": "cache_jsonrpc_response", "lineno": 111, "msecs": 50.43935775756836, "message": "jsonrpc error response", "name": "jussi.cache.cache_group", "timestamp": "2018-02-20T06:56:01.1519109761UTC", "severity": "INFO"}
{"timestamp":"2018-02-20T06:56:01+00:00","remote_addr":"195.201.61.139","request":"POST / HTTP/1.1","status":200,"body_bytes_sent":184,"request_time":5.514,"http_referrer":"-","http_user_agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"001106196993756281","x_jussi_response_time":"5.512908903998323","x_jussi_namespace":"conveyor","x_jussi_api":"False","x_jussi_method":"is_email_registered","x_jussi_params":"{'__signed': {'account': 'initminer', 'nonce': '9e93c79bf23ef73a', 'params': 'WyJkYWNvbS5k...pbC5jb20iXQ==', 'signatures': ['2067568e62b1...71c0262f4946c'], ...}}","upstream_connect_time":0.000,"upstream_response_time":5.514,"upstream_header_time":5.514,"upstream_response_length":184,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:01+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.000,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:04+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:09+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:15+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:24+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:34+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:44+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
{"timestamp":"2018-02-20T06:56:54+00:00","remote_addr":"172.17.0.1","request":"POST / HTTP/1.1","status":400,"body_bytes_sent":264,"request_time":0.001,"http_referrer":"-","http_user_agent":"dsteem/0.8.6","x_amzn_trace_id":"-","x_forwarded_for":"-","x_jussi_cache_hit":"-","x_jussi_request_id":"-","x_jussi_response_time":"-","x_jussi_namespace":"-","x_jussi_api":"-","x_jussi_method":"-","x_jussi_params":"-","upstream_connect_time":-,"upstream_response_time":-,"upstream_header_time":-,"upstream_response_length":-,"gzip_ratio":"-"}
```

Conveyor logs:
```
06:57:04.140Z ERROR conveyor: Unauthorized: Verification failed (HTTP 400: Bad Request) (req_id=914d3090-3f35-463f-9659-74881d1b5ad2, req_ip=::ffff:172.17.0.2, err.code=401)
    JsonRpcError: Unauthorized: Verification failed (HTTP 400: Bad Request)
        at Object.<anonymous> (/home/admin/conveyor/node_modules/@steemit/koa-jsonrpc/lib/auth.js:69:23)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
    Caused by: ValidationError: Verification failed (HTTP 400: Bad Request)
        at new ValidationError (/home/admin/conveyor/node_modules/@steemit/rpc-auth/lib/index.js:65:28)
        at Object.<anonymous> (/home/admin/conveyor/node_modules/@steemit/rpc-auth/lib/index.js:191:27)
        at step (/home/admin/conveyor/node_modules/@steemit/rpc-auth/lib/index.js:46:23)
        at Object.throw (/home/admin/conveyor/node_modules/@steemit/rpc-auth/lib/index.js:27:53)
        at rejected (/home/admin/conveyor/node_modules/@steemit/rpc-auth/lib/index.js:19:65)
        at process._tickDomainCallback (internal/process/next_tick.js:135:7)
    --
    rpc_req: {
      "id": 1106196993756281,
      "method": "conveyor.is_email_registered"
    }
```

What reason can be, if first step works correctly?

**Comment by dacom-dark-sun** [comment]
This problem assign with address prefix in koa-jsonrpc. In my local testnet i use prefix different with "STM", but Conveyour doesnot have this parameter in config for easy install.

**Comment by roadscape** [comment]
Hi @dacom-dark-sun, it sounds like there is no bug here, so I'm closing this bug. If you'd like to request a new configuration parameter you're welcome to create a new ticket.
